
name: flutter_mobile_starter
description: APP_DESCRIPTION.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  provider: ^6.0.0
  # dependency injection
  get_it: ^7.2.0
  # firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  firebase_analytics: ^10.1.4
  firebase_crashlytics: ^3.0.15
  firebase_dynamic_links: ^5.0.15
  # auth
  google_sign_in: ^6.0.1 
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.1
  # refresh
  pull_to_refresh: ^2.0.0
  # data management
  freezed_annotation:
  # formatting
  sprintf: ^7.0.0
  # styling
  ionicons: ^0.2.2
  # other
  stack_trace: ^1.10.0
  logging: ^1.1.1
  dartz: ^0.10.1
  injectable: ^2.1.0
  dio: ^5.0.1
  auto_route: ^5.0.4
  geoflutterfire2: ^2.3.15
  firebase_ui_auth: ^1.1.17
  firebase_ui_oauth_google: ^1.0.24
  firebase_ui_oauth_apple: ^1.0.24
  flex_color_scheme: ^6.1.2
  flutter_platform_widgets: ^3.2.0
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  geolocator: ^9.0.2
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  hive: ^2.2.3
  flutter_hooks: ^0.18.6
  path_provider: ^2.0.14
  image_picker: ^0.8.7+2
  image_cropper: ^3.0.2
  uuid: ^3.0.7
  reorderable_grid_view: ^2.2.6
  permission_handler: ^10.2.0
  url_launcher: ^6.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # other
  build_runner: ^2.1.2
  json_serializable: ^6.1.3
  freezed: ^2.3.2
  flutter_lints: ^2.0.1
  rename: ^2.0.1
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  injectable_generator: ^2.1.4
  auto_route_generator:

  

flutter:

  uses-material-design: true

  # assets:
  #   # emojis
  #   - assets/images/emojis/heart_emoji.png

  # fonts:
  # - family: IBMPlexMono
  #   fonts:
  #     - asset: assets/fonts/IBMPlexMono-Thin.ttf
  #       weight: 100